include("shared.lua")  
include("shared/sh_garlic_like.lua")  
include("shared/sh_garlic_like_scripted_ents.lua") 
include("client/cl_garlic_like.lua")  
include("client/cl_concommands.lua")
include("client/cl_fonts.lua")
include("client/cl_hooks.lua")
include("client/cl_menus1.lua")
include("client/cl_multicolor_text.lua")
include("client/cl_networking.lua")
include("client/cl_outline.lua")
include("client/cl_utils.lua")
include("shared/weaponselector/config.lua")
include("client/weaponselector/hooks.lua")
     
  